# Generated by Django 4.1.3 on 2022-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('hno', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('workExperience', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('fromDate', models.CharField(max_length=50)),
                ('toDate', models.CharField(max_length=50)),
                ('qualificationName', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
            ],
        ),
    ]
