# Generated by Django 4.1.3 on 2022-11-15 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='addresDetails',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
