# Generated by Django 4.1.3 on 2022-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='app1.category')),
            ],
        ),
    ]
